### ISSUE TITLE
Cannot Download Sample Data

### ISSUE THREAD

**Issue by QiSiyu** [lamdao/lmabr#1]
I tried to download the sample data from your dropbox shared link, but it turned out that the file isn't available anymore. Can you please share it again, or tell me how to prepare the data for your code? Thanks a lot!

**Comment by lamdao** [comment]
Please use following link to download sample data: https://drive.google.com/file/d/1jqnCtw8_Tv_9bvITIhAgKxJXgxqpJPnw/view

**Comment by QiSiyu** [comment]
> Please use following link to download sample data: https://drive.google.com/file/d/1jqnCtw8_Tv_9bvITIhAgKxJXgxqpJPnw/view

It works, thanks!
